### ISSUE TITLE
Todo card 기능 추가

### ISSUE THREAD

**Issue by kokocan12** [woowa-techcamp-2022/web-todo-6#23]
- todo card 드래그 시작 시 포인트 위치에 떠다니는 새로운 엘리먼트가 생성이 되어야 하므로 copy메소드를 정의하고 구현이 필요합니다~!(x, y 좌표 반영이 되었으면 좋겠어요)

- 드래그 종료 시 카드가 위치하면 삭제가 되어야하므로 destroy 메소드도 구현이 필요합니다~

**Comment by jstella96** [comment]
위 두기능은 완료되었습니다, 추가 기능은 새로운 이슈에서 추가하겠습니다.
#30
