### ISSUE TITLE
PR 메시지 컨벤션

### ISSUE THREAD

**Issue by kokocan12** [woowa-techcamp-2022/web-todo-6#6]
@jstella96 
PR 메시지 [] <-- 에 들어가는 키워드들 정리해주신다고 하셨던 거 위키에 남겨주세영

**Comment by jstella96** [comment]
했습니다~
[링크](https://github.com/woowa-techcamp-2022/web-todo-6/wiki/%EA%B7%9C%EC%B9%99)

**Comment by kokocan12** [comment]
> 했습니다~ [링크](https://github.com/woowa-techcamp-2022/web-todo-6/wiki/%EA%B7%9C%EC%B9%99)

확인했습니다.😊
